name: mottudeliveryapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  mottu_app_components:
    path: packages/mottu_app_components
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  golden_toolkit: ^0.13.0
  mockito: ^5.2.0
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/mottu_simbol.png

flutter_intl:
  enabled: true
